language: java
jdk:
- oraclejdk8

before_script:
 - sudo apt-get -qq update
 - sudo apt-get -qq install graphviz

script:
- mvn clean install javadoc:javadoc

after_success:
- mvn jacoco:prepare-agent test jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2
