language: java
jdk:
- oraclejdk8

before_script:
 - sudo apt-get -qq update
 - sudo apt-get -qq install graphviz

script:
- mvn clean install javadoc:javadoc
- dot --help

cache:
  directories:
    - $HOME/.m2